collection_name : agent
persist_directory : chroma_db_v1
k :  3
data_path : data
md5_hex_store : md5_v1.txt
allow_knowledge_file_type : ["txt","pdf"]

chunk_size : 700
chunk_overlap : 80
separators : ["\n\n","。",".","?","？","!"," ",""]
